import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { MouseProvider } from "./utils/MouseContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dahlia = localFont({
  src: "../../public/fonts/Dahlia-Regular.woff2",
  variable: "--font-dahlia",
  display: "swap",
});

const manrope = localFont({
  src: "../../public/fonts/manrope-v15-greek_latin-200.woff2",
  variable: "--font-manrope",
  display: "swap",
  weight: "200",
});

const quattrocento = localFont({
  src: "../../public/fonts/quattrocento-v21-latin-regular.woff2",
  variable: "--font-quattrocento",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dahlia.variable} ${manrope.variable} ${quattrocento.variable} antialiased`}
      >
        <MouseProvider>
          {children}
        </MouseProvider>
      </body>
    </html>
  );
}
